[tool.black]
line-length = 119
target-version = ["py310"]
extend-exclude = "(^/django_fsm_log/migrations/.*$|^docs/.*$)"

[tool.isort]
profile = "black"
py_version = 310
line_length = 119
skip_glob = "django_fsm_log/migrations/*"
