# Generated by Django 4.0.2 on 2022-04-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0004_auto_20190131_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='object_id',
            field=models.TextField(db_index=True),
        ),
    ]
